### ISSUE TITLE
heaty: Master switch -> AttributeError: 'str' object has no attribute 'is_off'

### ISSUE THREAD

**Issue by Omen90** [efficiosoft/hass_apps#1] opened 2018-02-05 19:17 UTC
Hi,

When I try the master switch turn off.

```
2018-02-05 19:52:05.854924 WARNING ------------------------------------------------------------
2018-02-05 19:52:05.856761 WARNING Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/appdaemon.py", line 512, in worker
    utils.sanitize_state_kwargs(args["kwargs"]))
  File "/usr/local/lib/python3.5/dist-packages/hass_apps/heaty/app.py", line 24, in _new_func
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hass_apps/heaty/app.py", line 175, in master_switch_cb
    scheduled=False)
  File "/usr/local/lib/python3.5/dist-packages/hass_apps/heaty/app.py", line 24, in _new_func
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hass_apps/heaty/app.py", line 441, in set_temp
    if target_temp.is_off():
AttributeError: 'str' object has no attribute 'is_off'

2018-02-05 19:52:05.859982 WARNING ------------------------------------------------------------
2018-02-05 19:52:05.860474 WARNING Logged an error to /home/homeassistant/conf/appdeamon.log
```
[appdaemon.log](https://github.com/efficiosoft/hass_apps/files/1696420/appdaemon.log)
[conf_apps.txt](https://github.com/efficiosoft/hass_apps/files/1696424/conf_apps.txt)

Home Assistant : 0.61.1
Heaty v0.9.4
AppDaemon 2.1.12

Thank you,

**Comment by efficiosoft** [comment] 2018-02-05 20:32
Thanks for reporting. Fix is included in latest release.

Best regards
Robert

**Closed** 2018-02-05 20:31 UTC

**Comment by efficiosoft** [comment] 2018-02-06 07:30
@Omen90  I have looked into it again and probably found the problem. Can you please upgrade to the latest version from GitHub? Just replacing ``config.py`` should suffice as well.

**Comment by Omen90** [comment] 2018-02-06 17:33
To be sure I have uninstalled hass_app, and made clean install. In the config file, I changed the default value on expr.OFF

`vol.Optional("off_temp", default=expr.OFF): TEMP_SCHEMA,`

Unfortunately, still the same warning.

[new.log](https://github.com/efficiosoft/hass_apps/files/1700113/new.log)

**Comment by Omen90** [comment] 2018-02-06 17:44
Okey, now everything is clear. If I add to the configuration (apps.yaml):
`off_temp: "off"` which should be the default value for off_temp, I don't get this warning anymore.

Now i have to find this off_temp value ->

```
2018-02-06 18:40:54.093816 INFO heaty_full: --- [Loft] Re-sending to climate.termostat in 30 seconds.
2018-02-06 18:41:15.300636 INFO heaty_full: --> [Loft] climate.termostat: attribute operation_mode is heat
2018-02-06 18:41:15.309234 INFO heaty_full: --> [Loft] climate.termostat: attribute temperature is 20.5
2018-02-06 18:41:15.316135 INFO heaty_full: --- Called update_publish_state_timer.
2018-02-06 18:41:16.026090 INFO heaty_full: <-- Publishing state to AppDaemon.
2018-02-06 18:41:24.017486 INFO heaty_full: --- [Loft] Cancelling retry timer for climate.termostat.
2018-02-06 18:41:24.023022 INFO heaty_full: <-- [Loft] Setting climate.termostat: temperature=<unset>, operation_mode=Off,
```

**Comment by efficiosoft** [comment] 2018-02-06 21:42
I think I finally got it now. Can you please retry with ``config.py`` from the master branch and without specifying ``off_temp`` in your configuration? Thanks.

**Comment by Omen90** [comment] 2018-02-06 22:15
Yeah, you got it 👍 

but we have something new...
First the master switch is off then on and next turned off again. 

```
2018-02-06 23:05:21.732311 INFO heaty_full: --> Master switch turned on.
2018-02-06 23:05:21.746504 INFO heaty_full: --- [Loft] Evaluated temperature expression 18.0 to 18.0.
2018-02-06 23:05:21.750720 INFO heaty_full: --- Called update_publish_state_timer.
2018-02-06 23:05:21.753867 INFO heaty_full: --- Called update_publish_state_timer.
2018-02-06 23:05:22.010604 INFO heaty_full: <-- Publishing state to AppDaemon.
2018-02-06 23:05:46.018101 INFO heaty_full: --- [Loft] Cancelling retry timer for climate.termostat.
2018-02-06 23:05:46.023820 INFO heaty_full: <-- [Loft] Setting climate.termostat: temperature=<unset>, operation_mode=Off, 
```
app is still cancelling retry timer...

Full log:
[log2306_060218.log](https://github.com/efficiosoft/hass_apps/files/1701000/log2306_060218.log)

**Comment by efficiosoft** [comment] 2018-02-07 09:10
Although this should be completely unrelated to the value of ``off_temp``, I see what caused the race condition. The problem is that your thermostat doesn't report back that it has been turned off. Can you please fetch ``app.py`` from master and try again?

With this fix in place Heaty will still re-send the turn off-command up to 10 times, but this is due to a misbehaviour of your thermostat. You could however reduce the number of retries in your config.

**Comment by Omen90** [comment] 2018-02-07 19:19
Understand. I did two tests. 
In apps.yaml : #off_temp (not declared) and set_temp_retries: 5

1. Turn on-> turn off - wait until 5 retries  -> turn on. - Fine

[log_with_5_left _to0.txt](https://github.com/efficiosoft/hass_apps/files/1704412/log_with_5_left._to0.txt)

2. Turn on-> turn off - wait for 2 re-sends -> turn on. I think its ok. Have a look in log. Still re-send the turn off-command but like you said It's because of my thermostat. After that we have normal `Called update_publish_state_timer`.

[log_with_5_left_to_4_and_turn_ms_on.txt](https://github.com/efficiosoft/hass_apps/files/1704415/log_with_5_left_to_4_and_turn_ms_on.txt)

Thank you.

**Comment by Omen90** [comment] 2018-02-07 19:44
One more thing.

I did all your last fixes in my app.py file from (hass_apps-0.20180205.2). That's because if I just copy the app.py file directly from master I have too many errors to fast fix. I can reinstall hass_apps when you will be ready to test final version. Here is my app.py:

[app.txt](https://github.com/efficiosoft/hass_apps/files/1704506/app.txt)

**Comment by efficiosoft** [comment] 2018-02-09 20:01
Ok, as far as I understand, everything is working as it should now, right?

The next release including all mentioned fixes is out now, hence you may now upgrade just as normal.

**Comment by Omen90** [comment] 2018-02-12 21:04
Tested with Home Assistant 0.63. Everything works perfectly.
